config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords'
  }
    devise_for :users, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }

  root to: "homes#about"

  namespace :admin do
    resources :users
    resources :books
  end
  namespace :public do
    resources :users
    resources :books
  end

  namespace :api do
    namespace :v1 do
      resources :books, only: %i[index]

      # 「/omniauth/sessions」へリダイレクトしてしまう場合はskip: [:omniauth_callbacks]を追記
      mount_devise_token_auth_for "User", at: "auth", skip: [:omniauth_callbacks], controllers: {
        registrations: 'api/v1/auth/registrations'
      }

      namespace :auth do
        resources :sessions, only: %i[index]
      end
    end
  end

  # devise_scope :admin do
  #   get 'admin/api/books', to: 'admin/books#index', defaults: { format: :json }
  # end

  # devise管理をしているモデルは「devise_scope :model名」を設定しないとroute errorが出る
  devise_scope :user do
    get 'public/api/books', to: 'public/books#index_api', defaults: { format: :json }
    get 'public/api/users', to: 'public/users#index_api', defaults: { format: :json }
  end

  get "home/about"=>"homes#about", as: "about"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules.
  # :trackable, :confirmable, :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
  include DeviseTokenAuth::Concerns::User

  has_one_attached :avatar
  has_many :books, dependent: :destroy
  belongs_to :role

  validates :name, presence:true

  def get_avatar(width, height)
    unless avatar.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      avatar.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    avatar.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  # ログインしていないときはログイン画面にリダイレクト
  before_action :authenticate_admin!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user.id), notice: "You have updated user successfully."
    else
      @books = @user.books
      render "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :role_id, :avatar)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model: @user, url: admin_user_path(@user.id), local: true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
     <div class="form-group">
        <%= f.label :avatar %>
        <%= image_tag @user.get_avatar(100,100) %><br>
        <%= f.file_field :avatar, class: "form-control-file avatar", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <div class="form-group">
        <%= f.label :role_id %>
        <%= f.collection_select :role_id, Role.all, :id, :name, options = { include_blank: false, selected: :role_id }, class: "form-control role_id" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/users/index.html.erb
<!-- ユーザーの一覧 -->

<% @users.each do |user| %>
<div>
  <%= link_to admin_user_path(user.id) do %>
    <%= image_tag user.get_avatar(100,100) %>
  <% end %>
  <p>
    名前：<%= link_to admin_user_path(user.id) do %>
      <%= user.name %>
    <% end %>
  </p>
  <p>ロール：<%= user.role_id %></p>
</div>
<% end %>

app/views/admin/users/show.html.erb
<!-- ユーザーの詳細 -->
<div>
  <h3><%= @user.name %></h3>
  <%= image_tag @user.get_avatar(100,100) %>
</div>

<%= link_to 'Edit', edit_admin_user_path(@user), class: "btn btn-sm btn-success edit_book_#{@user.id}" %>
<%= link_to edit_admin_user_path(@user), class: "btn btn-outline-secondary btn-block edit_user_#{@user.id}" do %>
  <i class="fas fa-user-cog"></i>
<% end %>

<!-- ユーザーの投稿一覧 -->

<% @books.each do |book| %>
<div>
  <%= link_to admin_book_path(book.id) do %>
    <%= image_tag book.get_image(63,63) %>
  <% end %>
  <p>タイトル：<%= book.title %></p>
  <p>説明：<%= book.body %></p>
  <p>ユーザーネーム：<%= book.user.name %></p>
</div>
<% end %>