config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords'
  }
    devise_for :users, controllers: {
    sessions:      'public/sessions',
    passwords:     'public/passwords',
    registrations: 'public/registrations'
  }

  root to: "homes#about"

  namespace :admin do
    resources :users
    resources :books
  end
  namespace :public do
    resources :users
    resources :books
  end

  namespace :api do
    namespace :v1 do
      resources :books, only: %i[index]

      # 「/omniauth/sessions」へリダイレクトしてしまう場合はskip: [:omniauth_callbacks]を追記
      mount_devise_token_auth_for "User", at: "auth", skip: [:omniauth_callbacks], controllers: {
        registrations: 'api/v1/auth/registrations'
      }

      namespace :auth do
        resources :sessions, only: %i[index]
      end
    end
  end

  # devise_scope :admin do
  #   get 'admin/api/books', to: 'admin/books#index', defaults: { format: :json }
  # end

  # devise管理をしているモデルは「devise_scope :model名」を設定しないとroute errorが出る
  devise_scope :user do
    get 'public/api/books', to: 'public/books#index_api', defaults: { format: :json }
    get 'public/api/users', to: 'public/users#index_api', defaults: { format: :json }
  end

  get "home/about"=>"homes#about", as: "about"
end

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MenterApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if user_signed_in? %>
        <li>
          <%= link_to "新規投稿", new_public_book_path %>
        </li>
        <li>
          <%= link_to "Books", public_books_path %>
        </li>
        <li>
          <%= link_to "Users", public_users_path %>
        </li>
        <li>
          <%= link_to "マイページ", public_user_path(current_user.id) %>
        </li>
        <li>
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
        </li>
      <% elsif admin_signed_in? %>
        <li>
          <%= link_to "新規投稿", new_admin_book_path %>
        </li>
        <li>
          <%= link_to "Books", admin_books_path %>
        </li>
        <li>
          <%= link_to "Users", admin_users_path %>
        </li>
        <li>
          <%= link_to "ログアウト", destroy_admin_session_path, method: :delete %>
        </li>
      <% else %>
        <li>
          <%= link_to "新規登録", new_user_registration_path %>
        </li>
        <li>
          <%= link_to "ログイン", new_user_session_path %>
        </li>
        <li>
          <%= link_to "管理者ログイン", new_admin_session_path %>
        </li>
        <li>
          <%= link_to "About", about_path %>
        </li>
      <% end %>
    </header>    <%= yield %>
  </body>
</html>